-- ================================================================
-- Database Initialization Script
-- ================================================================
-- This file combines all migration files into a single initialization script
-- Generated by merging: 001_init.sql, 002_add_multi_chain_support.sql, 
--                      003_add_user_custom_resources.sql, 004_remove_system_tables.sql
--

-- ================================================================
-- 1. UTILITY FUNCTIONS
-- ================================================================

-- Create update timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ================================================================
-- 2. CORE TABLES CREATION
-- ================================================================

-- Users table - Core user management
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Chains table - Blockchain networks configuration
CREATE TABLE IF NOT EXISTS chains (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    symbol VARCHAR(10) NOT NULL, -- Native token symbol (BNB, ETH, etc.)
    is_testnet BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    block_explorer_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Wallet groups table - User's wallet organization
CREATE TABLE IF NOT EXISTS wallet_groups (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

-- Wallet addresses table - Individual wallet addresses
CREATE TABLE IF NOT EXISTS wallet_addresses (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id INTEGER REFERENCES wallet_groups(id) ON DELETE SET NULL,
    address VARCHAR(42) NOT NULL,
    label VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, address)
);

-- Balance contracts table - Smart contracts for balance checking
CREATE TABLE IF NOT EXISTS balance_contracts (
    id SERIAL PRIMARY KEY,
    chain_id INTEGER NOT NULL REFERENCES chains(chain_id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    contract_address VARCHAR(42) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    priority INTEGER DEFAULT 0, -- Lower number = higher priority
    abi_json TEXT, -- Contract ABI storage
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(chain_id, contract_address)
);

-- User RPC endpoints table - User's custom RPC endpoints
CREATE TABLE IF NOT EXISTS user_rpc_endpoints (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    chain_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    url VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Unique constraints
    CONSTRAINT unique_user_rpc_url UNIQUE (user_id, chain_id, url)
);

-- User tokens table - User's custom token definitions
CREATE TABLE IF NOT EXISTS user_tokens (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    chain_id INTEGER NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    name VARCHAR(50) NOT NULL,
    contract_address VARCHAR(42) NOT NULL,
    decimals INTEGER NOT NULL DEFAULT 18,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Unique constraints
    CONSTRAINT unique_user_token_contract UNIQUE (user_id, chain_id, contract_address)
);

-- ================================================================
-- 3. INDEXES CREATION
-- ================================================================

-- Users table indexes
-- (Primary key index created automatically)

-- Chains table indexes
CREATE INDEX IF NOT EXISTS idx_chains_chain_id ON chains(chain_id);
CREATE INDEX IF NOT EXISTS idx_chains_is_active ON chains(is_active);

-- Wallet groups table indexes
CREATE INDEX IF NOT EXISTS idx_wallet_groups_user_id ON wallet_groups(user_id);

-- Wallet addresses table indexes
CREATE INDEX IF NOT EXISTS idx_wallet_addresses_user_id ON wallet_addresses(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_addresses_group_id ON wallet_addresses(group_id);

-- Balance contracts table indexes
CREATE INDEX IF NOT EXISTS idx_balance_contracts_chain_id ON balance_contracts(chain_id);
CREATE INDEX IF NOT EXISTS idx_balance_contracts_priority ON balance_contracts(priority);
CREATE INDEX IF NOT EXISTS idx_balance_contracts_is_active ON balance_contracts(is_active);

-- User RPC endpoints table indexes
CREATE INDEX IF NOT EXISTS idx_user_rpc_user_id ON user_rpc_endpoints(user_id);
CREATE INDEX IF NOT EXISTS idx_user_rpc_chain_id ON user_rpc_endpoints(chain_id);
CREATE INDEX IF NOT EXISTS idx_user_rpc_active ON user_rpc_endpoints(is_active);

-- User tokens table indexes
CREATE INDEX IF NOT EXISTS idx_user_token_user_id ON user_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_user_token_chain_id ON user_tokens(chain_id);
CREATE INDEX IF NOT EXISTS idx_user_token_active ON user_tokens(is_active);
CREATE INDEX IF NOT EXISTS idx_user_token_contract ON user_tokens(contract_address);

-- ================================================================
-- 4. TRIGGERS CREATION
-- ================================================================

-- Users table trigger
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON users
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Chains table trigger
DROP TRIGGER IF EXISTS update_chains_updated_at ON chains;
CREATE TRIGGER update_chains_updated_at 
    BEFORE UPDATE ON chains
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Wallet groups table trigger
DROP TRIGGER IF EXISTS update_wallet_groups_updated_at ON wallet_groups;
CREATE TRIGGER update_wallet_groups_updated_at 
    BEFORE UPDATE ON wallet_groups
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Wallet addresses table trigger
DROP TRIGGER IF EXISTS update_wallet_addresses_updated_at ON wallet_addresses;
CREATE TRIGGER update_wallet_addresses_updated_at 
    BEFORE UPDATE ON wallet_addresses
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Balance contracts table trigger
DROP TRIGGER IF EXISTS update_balance_contracts_updated_at ON balance_contracts;
CREATE TRIGGER update_balance_contracts_updated_at 
    BEFORE UPDATE ON balance_contracts
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- User RPC endpoints table trigger
DROP TRIGGER IF EXISTS trigger_user_rpc_endpoints_updated_at ON user_rpc_endpoints;
CREATE TRIGGER trigger_user_rpc_endpoints_updated_at
    BEFORE UPDATE ON user_rpc_endpoints
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- User tokens table trigger
DROP TRIGGER IF EXISTS trigger_user_tokens_updated_at ON user_tokens;
CREATE TRIGGER trigger_user_tokens_updated_at
    BEFORE UPDATE ON user_tokens
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ================================================================
-- 5. INITIAL DATA INSERTION
-- ================================================================

-- Insert blockchain networks data
INSERT INTO chains (chain_id, name, symbol, is_testnet, is_active, block_explorer_url) VALUES
(56, 'BSC Mainnet', 'BNB', FALSE, TRUE, 'https://bscscan.com'),
(97, 'BSC Testnet', 'tBNB', TRUE, TRUE, 'https://testnet.bscscan.com'),
(1, 'Ethereum Mainnet', 'ETH', FALSE, TRUE, 'https://etherscan.io'),
(5, 'Ethereum Goerli', 'ETH', TRUE, FALSE, 'https://goerli.etherscan.io'),
(137, 'Polygon Mainnet', 'MATIC', FALSE, TRUE, 'https://polygonscan.com'),
(80001, 'Polygon Mumbai', 'MATIC', TRUE, FALSE, 'https://mumbai.polygonscan.com')
ON CONFLICT (chain_id) DO NOTHING;

-- Insert BalanceChecker contract addresses
INSERT INTO balance_contracts (chain_id, name, contract_address, priority) VALUES
(56, 'BalanceChecker BSC', '0x0ab68be1431cd1E6Fd86793C6392181eb4dc636b', 1),
(97, 'BalanceChecker BSC Testnet', '0x0ab68be1431cd1E6Fd86793C6392181eb4dc636b', 1)
ON CONFLICT (chain_id, contract_address) DO NOTHING;

-- ================================================================
-- END OF INITIALIZATION SCRIPT
-- ================================================================

-- Script completion message
-- This script successfully creates all required tables, indexes, triggers,
-- and initial data for the wallet balance query application.
--
-- Tables created:
-- - users (user management)
-- - chains (blockchain networks)
-- - wallet_groups (wallet organization)
-- - wallet_addresses (individual addresses)
-- - balance_contracts (balance checking contracts)
-- - user_rpc_endpoints (user's custom RPC endpoints)
-- - user_tokens (user's custom token definitions)
--
-- Note: This script is idempotent and can be run multiple times safely.